apiVersion: batch/v1
kind: CronJob
metadata:
  name: statustracker
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: statustracker
              image: statustracker
              env:
                - name: CONN_STRING
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: conn_string
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: webhook_url
          restartPolicy: OnFailure