apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nautilus-statustracker

images:
  - name: statustracker
    newName: us-central1-docker.pkg.dev/devspace1/nautilus/statustracker
    newTag: "e5abc71"

resources:
  - namespace.yaml

  - secret.yaml
  - cronjob.yaml